apiVersion: batch/v1
kind: CronJob
metadata:
  name: ovh-dns-updater-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ovh-dns-updater
        spec:
          containers:
          - name: ovh-dns-updater
            image: your-ovh-dns-updater-image:latest
            env:
            - name: OVH_ENDPOINT
              value: "ovh-eu"
            - name: OVH_APPLICATION_KEY
              value: ""
            - name: OVH_APPLICATION_SECRET
              value: ""
            - name: OVH_CONSUMER_KEY
              value: ""
            volumeMounts:
            - name: data-volume
              mountPath: "/data"
          restartPolicy: "OnFailure"
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: data-pv-claim